version: "3.0"

services:
  frontend:
    build:
      context: ./frontend
    container_name: trinity_frontend
    networks:
      - portfolio
    ports:
      - 5556:3000
  
  backend:
    build:
      context: ./backend
    networks:
      - portfolio
    ports:
      - 5557:5557

networks:
  portfolio:
    driver: bridge