version: "3.0"

services:
  frontend:
    build:
      context: ./frontend
    network_mode: bridge
    ports:
      - 5556:3000
  
  backend:
    build:
      context: ./backend
    network_mode: bridge
    ports:
      - 5557:5557