CREATE DATABASE portfolio default CHARACTER SET UTF8;

CREATE TABLE ACT (
    A_id SMALLINT unsigned PRIMARY KEY AUTO_INCREMENT,
    start MEDIUMINT unsigned NOT NULL,
    end MEDIUMINT unsigned NOT NULL,
    company VARCHAR(32) NOT NULL,
    name VARCHAR(32) NOT NULL,
    content VARCHAR(256) NOT NULL,
    tect VARCHAR(32) NOT NULL
) ENGINE=INNODB;

CREATE TABLE PORTFOLIO (
     P_id SMALLINT unsigned PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(32) NOT NULL,
    content VARCHAR(256) NOT NULL,
    href VARCHAR(512) NOT NULL,
    tect VARCHAR(32) NOT NULL,
    role VARCHAR(32) NOT NULL,
    date MEDIUMINT unsigned NOT NULL
) ENGINE=INNODB;